# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naukri', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='email_address',
            new_name='email',
        ),
    ]
