# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naukri', '0002_auto_20170613_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_sector',
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(max_length=100),
        ),
    ]
